server:
  listen: ":10900"

svgs:
  default:
    width: 800
    font_size: 16
    rows:
      - type: text
        text: "Custom static content"
      # - type: header
      #   name: "X-Request-ID"
      #   label: "Request ID"
      - type: header
        name: "Cf-Connecting-Ip"
        label: "Client IP"
      - type: header
        name: "User-Agent"
        label: "User Agent"
      - type: query
        name: "user"
        label: "User"
      - type: query
        label: "All Query"
  a:
    width: 800
    font_size: 16
    rows:
      - type: header
        name: "Cf-Connecting-Ip"
        label: "Client IP"
      - type: header
        name: "User-Agent"
        label: "User Agent"
      - type: query
        label: "param"

  debug:
    width: 1000
    font_size: 14
    rows:
      - type: text
        text: "Debug SVG"
      - type: header
        name: "User-Agent"
      - type: query
        name: "trace"
